### ISSUE TITLE
Start Game logic to add and subtract Chips from Player depending on what they roll

### ISSUE THREAD

**Issue by eg22453** [bratwurst-productions/LCR-Game#42]

**Comment by lonesomecowboy42** [comment]
there are still some issues with this. for example, sometimes firebase will evidently drop changes that it thinks are duplicates. This issue could probably be fixed by transactionalizing (i.e., sending firebase a JSON object instead of individual changes) after a complete roll, rather than sending incremental updates in the dice roll loop. But that will he handled in a separate issue ticket.
